name: Execute Script
on:
  push:
    branches:
      - main
jobs:
  cheeck-and-create-qm:
   runs-on: self-hosted
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Checking & Creating Queue Manager
       shell: bash
       id: execute-script
       continue-on-error: true
       run: |
        bash deploy-qm.sh
        echo "::set-output name=exit-code::$?"
        echo "$?"
        echo "${{ steps.execute-script.outputs.exit-code == '0' }}"
     - name: Take action based on exit code
       if: ${{ steps.execute-script.outputs.exit-code == '0' }}
       run: echo "Queue Manager was created succeeded"
     - name: Notify on failure
       if: ${{ steps.execute-script.outputs.exit-code != '0' }}
       run: echo "There is an issue with creating Queue Manager"
     - name: Send mail
       uses: dawidd6/action-send-mail@v3
       with:
         # Required mail server address if not connection_url:
         connection_url: smtp://bharathmanikanta.gundapu@eidiko-india.com:Bharathg@123@mail.eidiko-india.com:587
         #connection_url: smtp+starttls://user:password@mail.eidiko-india.com:587
         server_address: mail.eidiko-india.com
         # Server port, default 25:
         server_port: 587
         # Optional whether this connection use TLS (default is true if server_port is 465)
         secure: true
         subject: Github Actions job result
         # Required recipients' addresses:
         to: bharathmanikanta.gundapu@eidiko-india.com
        # Required sender full name (address can be skipped):
         from: Luke Skywalker # <bharathmanikanta.gundapu@eidiko-india.com>
        # Optional plain body:
         body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        # Optional carbon copy recipients:
         cc: bharathmanikanta.gundapu@eidiko-india.com
        # Optional blind carbon copy recipients:
         bcc: bharathmanikanta.gundapu@eidiko-india.com
        # Optional recipient of the email response:
         reply_to: bharathmanikanta.gundapu@eidiko-india.com
        # Optional Message ID this message is replying to:
         in_reply_to: bharathmanikanta.gundapu@eidiko-india.com
        # Optional unsigned/invalid certificates allowance:
         ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
         convert_markdown: true
        # Optional attachments:
         attachments: attachments.zip,git.diff,./dist/static/*.js
        # Optional priority: 'high', 'normal' (default) or 'low'
         priority: low
     - name: Wait for 4 Minutes
       run: sleep 240
       
 
