name: Execute Script
on:
  push:
    branches:
      - main
jobs:
  cheeck-and-create-qm:
   runs-on: self-hosted
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Checking & Creating Queue Manager
       shell: bash
       id: execute-script
       continue-on-error: true
       run: |
        bash deploy-qm.sh
        echo "::set-output name=exit-code::$?"
        echo "$?"
        echo "${{ steps.execute-script.outputs.exit-code == '0' }}"
     - name: Take action based on exit code
       if: ${{ steps.execute-script.outputs.exit-code == '0' }}
       run: echo "Queue Manager was created succeeded"
     - name: Notify on failure
       if: ${{ steps.execute-script.outputs.exit-code != '0' }}
       run: echo "There is an issue with creating Queue Manager"
     - name: Send mail
       uses: dawidd6/action-send-mail@v3
       with:
         connection_url: smtp://bharathmanikanta.gundapu@eidiko-india.com:Bharathg@123@mail.eidiko-india.com:587
         #connection_url: smtp+starttls://user:password@mail.eidiko-india.com:587
         server_address: mail.eidiko-india.com
         server_port: 587
         secure: true
         subject: Github Actions job result
         to: bharathmanikanta.gundapu@eidiko-india.com
         from: Luke Skywalker # <bharathmanikanta.gundapu@eidiko-india.com>
         body: Build job of ${{github.repository}} completed successfully!
         cc: bharathmanikanta.gundapu@eidiko-india.com
         bcc: bharathmanikanta.gundapu@eidiko-india.com
         reply_to: bharathmanikanta.gundapu@eidiko-india.com
         in_reply_to: bharathmanikanta.gundapu@eidiko-india.com
         ignore_cert: true
         convert_markdown: true
         attachments: attachments.zip,git.diff,./dist/static/*.js
         priority: low
     - name: Request approval
       uses: peter-evans/create-issue-from-file@v2
       with:
         title: 'Approval Required: ${{ github.event.pull_request.title }}'
         body: |
           Please review and approve this pull request.
           assignees: veeru1414, tirapa-eidiko
     - name: Wait for 4 Minutes
       run: sleep 240
       
 
