name: Execute Script
on:
  push:
    branches:
      - main
jobs:
  cheeck-and-create-qm:
   runs-on: self-hosted
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Checking & Creating Queue Manager
       shell: bash
       id: execute-script
       continue-on-error: true
       run: |
        bash deploy-qm.sh
        echo "::set-output name=exit-code::$?"
        echo "$?"
        echo "${{ steps.execute-script.outputs.exit-code == '0' }}"
     - name: Take action based on exit code
       if: ${{ steps.execute-script.outputs.exit-code == '0' }}
       run: echo "Queue Manager was created succeeded"
     - name: Notify on failure
       if: ${{ steps.execute-script.outputs.exit-code != '0' }}
       run: echo "There is an issue with creating Queue Manager"
     - name: Wait for 4 Minutes
       run: sleep 240
 
