name: Execute Script
on:
  push:
    branches:
      - main
jobs:
  example-job:
   runs-on: self-hosted
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Clean Up Queue Manager
       shell: bash
       id: execute-script
       continue-on-error: true
       run: |
        bash ../cleanup.sh
        pwd
        ls
        cd ..
        pwd
        ls
        echo "::set-output name=exit-code::$?"
        echo "$?"
        echo "${{ steps.execute-script.outputs.exit-code == '0' }}"
     - name: Take action based on exit code
       if: ${{ steps.execute-script.outputs.exit-code == '0' }}
       run: echo "Script succeeded"
     - name: Notify on failure
       if: ${{ steps.execute-script.outputs.exit-code != '0' }}
       run: echo "Script failed"
