name: Execute Script
on:
  push:
    branches:
      - main
jobs:
  example-job:
   runs-on: self-hosted
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Run build script
       run: sh /home/bandaru/git-act/scripts.sh
       shell: bash
     - name: Clean Up Queue Manager
       shell: bash
       id: execute-script
       continue-on-error: true
       run: |
        bash ../cleanup.sh
        echo "::set-output name=exit-code::$?"
