name: Execute Script
on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    runs-on: 'self-hosted'
    environment: 'dev'
    needs: cheeck-and-create-qm
    steps:
      - name: Deploy in DEV
        run: echo "Development Deployment Done Successfully"
  deploy-uat:
    runs-on: 'self-hosted'
    environment: 'uat'
    needs: [cheeck-and-create-qm, deploy-dev]
    steps:
      - name: Deploy in UAT
        run: echo "UAT Deployment Done Successfully"
  deploy-prod:
    runs-on: 'self-hosted'
    environment: 'prod'
    needs: [cheeck-and-create-qm, deploy-dev,deploy-uat]
    steps:
      - name: Deploy in Production
        run: echo "Prodcution Deployment Done Successfully"

  cheeck-and-create-qm:
   runs-on: self-hosted
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Checking & Creating Queue Manager
       shell: bash
       id: execute-script
       continue-on-error: true
       run: |
        bash deploy-qm.sh
        echo "::set-output name=exit-code::$?"
        echo "$?"
        echo "${{ steps.execute-script.outputs.exit-code == '0' }}"
     - name: Take action based on exit code
       if: ${{ steps.execute-script.outputs.exit-code == '0' }}
       run: echo "Queue Manager was created succeeded"
     - name: Notify on failure
       if: ${{ steps.execute-script.outputs.exit-code != '0' }}
       run: echo "There is an issue with creating Queue Manager"
     - name: Send mail
       uses: dawidd6/action-send-mail@v3
       with:
         connection_url: smtp://bharathmanikanta.gundapu@eidiko-india.com:Bharathg@123@mail.eidiko-india.com:587
         #connection_url: smtp+starttls://user:password@mail.eidiko-india.com:587
         server_address: mail.eidiko-india.com
         server_port: 587
         secure: true
         subject: Github Actions job result
         to: bharathmanikanta.gundapu@eidiko-india.com
         from: Luke Skywalker # <bharathmanikanta.gundapu@eidiko-india.com>
         body: Build job of ${{github.repository}} completed successfully!
         cc: bharathmanikanta.gundapu@eidiko-india.com
         bcc: bharathmanikanta.gundapu@eidiko-india.com
         reply_to: bharathmanikanta.gundapu@eidiko-india.com
         in_reply_to: bharathmanikanta.gundapu@eidiko-india.com
         ignore_cert: true
         convert_markdown: true
         attachments: attachments.zip,git.diff,./dist/static/*.js
         priority: low
     - name: Wait for 4 Minutes
       run: sleep 240
       
 
