name: Execute Script
on:
  push:
    branches:#testing
      - main
jobs:
  example-job:
   runs-on: self-hosted
   steps:
     - name: Run build script
       run: sh /home/bandaru/git-act/scripts.sh
       shell: bash
