name: CD Pipeline
on:
  release:
    types: [published, edited]
    tags:
      - 'v\d+\.\d+\.\d+'
jobs:
  release-pipeline:
    runs-on: self-hosted
    steps:
      - name: Get release info
        uses: actions/github-script@v5
        id: get_release_info
        with:
          result-encoding: string
          script: |
            console.log(`Release name: ${context.payload.release.tag_name}`);
            console.log(`Release tag: ${context.payload.release}`);
            console.log(context)
            return `${context.payload.release.tag_name}`;
      - name: Print release info
        run: |
          echo "Release name: ${{ steps.get_release_info.outputs.result }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Execute Integration Server Deploy Script
        shell: bash
        id: execute-server-script 
        continue-on-error: true
        run: |
         bash deploy-ace-server.sh ${{ vars.NAMESPACE }} ${{ steps.get_release_info.outputs.result }}


